jobs:

# runCI job that builds and pushes artifact to Amazon ECR
  - name: node-ecr-deploy-ecs-loadbalancer_runCI
    type: runCI
    steps:
      - OUT: shipdemo-img-ecs
    flags:
      - amazon-ecr-ecs-loadbalancer

# generate manifest
  - name: shipdemo-manifest-ecs
    type: manifest
    steps:
      - IN: shipdemo-img-ecs
      - IN: shipdemo-img-options-ecs-test
      - TASK: managed
    flags:
      - amazon-ecr-ecs-loadbalancer

# Create TEST Release


# TEST deployment to Amazon ECS
  - name: shipdemo-deploy-ecs-test
    type: deploy
    steps:
#      - IN: shipdemo-release-ecs-beta
#      - IN: shipdemo-params-ecs-test
      - IN: shipdemo-cluster-ecs
      - IN: shipdemo-alb-test
        applyTo:
          - manifest: shipdemo-manifest-ecs
            image: shipdemo-img-ecs
            port: 80
      - TASK: managed
    flags:
      - amazon-ecr-ecs-loadbalancer
